
CFILES=osslsigncode.c msi.c
OBJECTS=$(patsubst %.c,%.o,${CFILES})
C_FLAGS=-DENABLE_CURL=1 -DHAVE_CONFIG_H=1 -I. 
LINK_FLAGS=-Wall
all:osslsigncode


osslsigncode:$(OBJECTS)
	gcc ${LINK_FLAGS} -o osslsigncode $(OBJECTS) -lssl -lcrypto -lcurl

osslsigncode.o:osslsigncode.c

msi.o:msi.c

%.o:%.c
	gcc ${C_FLAGS} -o $@ -c $<

clean:
	rm -f ${OBJECTS} osslsigncode